version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - revive
    - ineffassign  
    - prealloc
    - unparam
    - gosec
  settings:
   gocyclo:
    min-complexity: 15


issues:
  max-issues-per-linter: 0
  max-same-issues: 0

