name: ci
on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md', '**/*.png', '**/*.jpg' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true  

    
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0     
          args: --timeout=3m

      - name: Test (race + coverage)
        run: go test ./... -race -coverprofile=coverage.out
